name:base

channels:
  - conda-forge
  - defaults
dependencies:
  - elasticsearch=7.0.0=py_0
  - invoke=1.2.0=py37_1000
  - markdown=2.6.11=py_0
  - nbconvert=5.5.0=py_0
  - newrelic=4.20.1.121=py37h516909a_0
  - pandoc=2.7.3=0
  - pycurl=7.43.0.2=py37h16ce93b_1
  - pylibmc=1.6.0=py37h14c3975_1000
  - statsd=3.3.0=py_0
