package:
  name: ijavascript
  version: "v5.0.20"

source:
  git_rev: v5.0.20
  git_url: https://github.com/n-riesco/ijavascript.git

requirements:
  build:
    - nodejs
  run:
    - nodejs
    - jupyter

about:
  home: https://github.com/n-riesco/ijavascript
  license: "BSD 3-clause"
  license_file: LICENSE
  creator: "Nicolas Riesco"