{% set jupyterlab_version = ">=2.0.0,<3.0.0" %}
{% set version = "5.0.8" %}

package:
  name: jupyterlab-toc
  version: {{ version }}

source:
  git_url: https://github.com/krinsman/jupyterlab-toc.git
  get_rev: {{ version }}
  git_depth: 1

requirements:
  build:
    - jupyterlab{{ jupyterlab_version }}
  run:
    - jupyterlab{{ jupyterlab_version }}

about:
  home: https://github.com/jupyterlab/jupyterlab-toc
  license: "BSD 3-Clause"
  license_file: LICENSE
  creator: "Ian Rose"