{% set jupyterlab_version = "" %}
{% set version = "" %}

package:
  name: 
  version: {{ version }}

source:
  git_url: 

requirements:
  build:
    - jupyterlab>={{ jupyterlab_version }}
  run:
    - jupyterlab>={{ jupyterlab_version }}

about:
  home: 
  license: 
  license_file: 
  creator: 