package:
  name: jupyterlab-latex
  version: "0.4.0"

source:
  git_url: https://github.com/jupyterlab/jupyterlab-latex.git
  git_rev: "0.4.0"

requirements:
  build:
    - nodejs
    - jupyterlab
  run:
    - nodejs
    - jupyterlab
<<<<<<< HEAD

about:
  home: https://github.com/jupyterlab/jupyterlab-latex
  license: "BSD 3-Clause"
  license_file: LICENSE
  creator: "Jupyter Development Team"
=======
>>>>>>> 126eef7... jupyterlab-latex
