package:
  name: jupyterlab-toc
  version: "v0.3.1"

source:
  git_url: https://github.com/jupyterlab/jupyterlab-toc.git

requirements:
  build:
    - nodejs
    - jupyterlab>=0.33.4
  run:
    - nodejs
    - jupyterlab>=0.33.4

about:
  home: https://github.com/jupyterlab/jupyterlab-toc
  license: "BSD 3-Clause"
  license_file: LICENSE
  creator: "Ian Rose"