package:
  name: jupyterlab-github
  version: "v0.7.1"

source:
  git_url: https://github.com/jupyterlab/jupyterlab-github.git

requirements:
  build:
    - nodejs
    - jupyterlab>=0.33.4
  run:
    - nodejs
    - jupyterlab>=0.33.4

about:
  home: https://github.com/jupyterlab/jupyterlab-github
  license: "BSD 3-Clause"
  license_file: LICENSE
  creator: "JupyterLab team"