package:
  name: jupyterlab_html
  version: "v0.1.0"

source:
  git_url: https://github.com/mflevine/jupyterlab_html.git

requirements:
  build:
    - nodejs
    - jupyterlab>=0.33.4
  run:
    - nodejs
    - jupyterlab>=0.33.4

about:
  home: https://github.com/mflevine/jupyterlab_html
  license: "BSD 3-Clause"
  license_file: LICENSE
  creator: "Max Levine"