{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lobstr
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/r-lib/lobstr

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, pillar, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{native}}toolchain          # [win]
    - {{posix}}filesystem          # [win]
    - {{posix}}git

  host:
    - r-base
    - r-cli
    - r-crayon
    - r-rcpp >=0.12.7
    - r-rlang >=0.1.2

  run:
    - r-base
    - r-rcpp >=0.12.7
    - r-rlang >=0.1.2
    - r-cli
    - r-crayon

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('lobstr')"           # [not win]
    - "\"%R%\" -e \"library('lobstr')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/r-lib/lobstr/blob/master/DESCRIPTION
  license: GPL-3
  summary: Visualise R data structures with trees. A set of tools for inspecting and understanding complex R data structures. Inspired by `str()`.
  license_family: GPL

# The original CRAN metadata for this package was:

# Package: lobstr
# Title: Visualise R data structures with trees
# Version: 0.0.0.9000
# Authors@R: c(
#     person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")),
#     person("RStudio", role = "cph")
#   )
# Description: A set of tools for inspecting and understanding complex R data
#     structures. Inspired by `str()`.
# License: GPL-3
# URL: https://github.com/r-lib/lobstr
# BugReports: https://github.com/r-lib/lobstr/issues
# Depends: 
#     R (>= 3.1)
# Imports: 
#     cli,
#     crayon,
#     Rcpp,
#     rlang
# Suggests: 
#     covr,
#     pillar,
#     testthat
# LinkingTo: 
#     Rcpp
# Encoding: UTF-8
# LazyData: true
# Roxygen: list(markdown = TRUE)
# RoxygenNote: 6.0.1

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
