{% set version = '1.0.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-sl3
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/tlverse/sl3

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, pillar, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{native}}toolchain          # [win]
    - {{posix}}filesystem          # [win]
    - {{posix}}git

  host:
    - r-base >=2.14.0
    - r-data.table
    - r-assertthat
    - r-origami
    - r-r6
    - r-uuid
    - r-bbmisc
    - r-delayed
    - r-ggplot2
    - r-condensier
    - r-testthat
    - r-superlearner
    - r-future
    - r-devtools
    - r-dplyr

  run:
    - r-base >=2.14.0
    - r-data.table
    - r-assertthat
    - r-origami
    - r-r6
    - r-uuid
    - r-bbmisc
    - r-delayed
    - r-ggplot2
    - r-condensier
    - r-testthat
    - r-superlearner
    - r-future
    - r-devtools
    - r-dplyr

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('sl3')"           # [not win]
    - "\"%R%\" -e \"library('sl3')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/tlverse/sl3
  license: GPL-3
  summary: Implements the super learner prediction method and contains a library of prediction algorithms to be used in the super learner.
  license_family: GPL

# The original GitHub metadata for this package was:

# Package: sl3
# Title: Pipelines for Machine Learning and Super Learning
# Version: 1.0.0
# Authors@R: c(
#     person("Jeremy", "Coyle", email = "jeremyrcoyle@gmail.com",
#            role = c("aut", "cre", "cph")),
#     person("Nima", "Hejazi", email = "nh@nimahejazi.org", role = "aut"),
#     person("Oleg", "Sofrygin", email="oleg.sofrygin@gmail.com", role = "aut"),
#     person("Ivana", "Malenica", email = "imalenica@berkeley.edu", role = "aut")
#   )
# Maintainer: Jeremy Coyle <jeremyrcoyle@gmail.com>
# Description: Implements the super learner prediction method and contains a
#     library of prediction algorithms to be used in the super learner.
# Depends: R (>= 2.14.0)
# Imports:
#     data.table,
#     assertthat,
#     origami,
#     R6,
#     uuid,
#     BBmisc,
#     stats,
#     delayed,
#     utils,
#     methods,
#     ggplot2
# Suggests:
#     testthat,
#     knitr,
#     rmarkdown,
#     glmnet,
#     devtools,
#     dplyr,
#     drat,
#     rgl,
#     condensier,
#     cvAUC,
#     forecast,
#     nloptr,
#     rugarch,
#     nnls,
#     tsDyn,
#     Rsolnp,
#     xgboost,
#     speedglm,
#     randomForest,
#     SuperLearner,
#     h2o,
#     future,
#     e1071,
#     earth,
#     R.rsp,
#     kerasR,
#     keras,
#     reticulate
# Remotes:
#     github::osofr/condensier,
#     github::tlverse/delayed
# License: GPL-3
# URL: https://sl3.tlverse.org
# BugReports: https://github.com/tlverse/sl3/issues
# Encoding: UTF-8
# LazyData: yes
# LazyLoad: yes
# VignetteBuilder:
#     knitr,
#     R.rsp
# RoxygenNote: 6.0.1.9000
# Roxygen: list(markdown = TRUE)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
