{% set version = '0.0.0.9000' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-screening
  version: {{ version|replace("-", "_") }}

source:

  git_url: https://github.com/wwrechard/screening

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, pillar, testthat
requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ compiler('cxx') }}        # [not win]
    - {{native}}toolchain          # [win]
    - {{posix}}filesystem          # [win]
    - {{posix}}git

  host:
    - r-base >=3.2.2

  run:
    - r-base >=3.2.2

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('screening')"           # [not win]
    - "\"%R%\" -e \"library('screening')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://github.com/wwrechard/screening/blob/master/DESCRIPTION
  license: No license
  summary: An R package for efficient variable screening for linear and generalized linear models.

# The original CRAN metadata for this package was:

# Package: screening
# Title: What the Package Does (one line, title case)
# Version: 0.0.0.9000
# Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
# Description: What the package does (one paragraph).
# Depends:
#     R (>= 3.2.2)
# License: What license is it under?
# LazyData: true
# RoxygenNote: 5.0.0.9000

# See also the readme on Github: https://github.com/wwrechard/screening/blob/master/README.md

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
